controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '|fr|en'
    defaults:
        _locale: fr

Agent:
    resource: ../../src/Agent/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
